[package]
name = "hyprconnect_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
hyprconnect_core = { path = "../hyprconnect_core" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.43", features = ["full"] }

